######################################################################
#
# File name : full_adder_using_two_half_adder_tb.udo
# Created on: Sun Jul 28 19:57:44 +0500 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
