######################################################################
#
# File name : full_adder_using_two_half_adder_tb_simulate.do
# Created on: Sun Jul 28 19:57:44 +0500 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.full_adder_using_two_half_adder_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {full_adder_using_two_half_adder_tb_wave.do}

view wave
view structure
view signals

do {full_adder_using_two_half_adder_tb.udo}

run 1000ns
