######################################################################
#
# File name : full_adder_using_two_half_adder_tb_compile.do
# Created on: Sun Jul 28 19:57:40 +0500 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../full_adder_using_two_half_adder.srcs/sources_1/new/full_adder_using_two_half_adder.v" \
"../../../../full_adder_using_two_half_adder.srcs/sources_1/new/half_adder.v" \
"../../../../full_adder_using_two_half_adder.srcs/sim_1/new/full_adder_using_two_half_adder_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

